services:
  - type: web
    name: langfight
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python LangFight.py
    envVars:
      - key: PORT
        sync: false
      - key: HOST
        value: 0.0.0.0
